name: Lint & Build Testing

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Setup Node
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run lint

      - name: Build Next.js app
        run: pnpm run build
